# Generated by Django 3.0.3 on 2020-08-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiods',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activityperiods',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
